name: Build and Deploy Rustdoc

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.96.0

      - name: Build Rustdoc
        run: cargo doc --no-deps --all-features

      - name: Create redirect index.html
        run: |
          CRATE_NAME=$(grep '^name =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo '<meta http-equiv="refresh" content="0; url='"$CRATE_NAME"'/index.html">' > target/doc/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
